name: Linux_workflow

on: [push]

jobs:
 
  build_mac_ARM64:

    runs-on: [macos-latest, ARM64]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
          
      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -o mac/rubixgoplatform_arm64


