name: Windows_workflow

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
          
      - name: Cache Go modules
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
            
    #  - name: Install dependencies
    #    run: go get .

      - name: Build
        run: go build
        
      - uses: actions/upload-artifact@v3
        with:
         name: rubixwindows
         path: windows/
        
       

