name: Windows_workflow

on: [push]

jobs:
  build:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
          
      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -o windows/rubixgoplatform.exe
        
      - uses: actions/upload-artifact@v3
        with:
         path: windows/
         
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          
      - name: Use Application Token to create a release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        with:
         title: MyReleaseMessage
      
